sudo: false
language: node_js
node_js:
   - "0.10"
   - "0.12"
   - "4"
   - "stable"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4a4dea774d3ac86cfef1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
